// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu87FfSOfe1uvCG_AW-r4hkywGCFAsnag',
    appId: '1:994401444079:web:a1b2a1e3b458568145fb1a',
    messagingSenderId: '994401444079',
    projectId: 'ecom-e55f5',
    authDomain: 'ecom-e55f5.firebaseapp.com',
    storageBucket: 'ecom-e55f5.appspot.com',
    measurementId: 'G-36PP4PHMLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMUk1MapZ1_C7GK6D5UsRb3QdsYJDBTzM',
    appId: '1:994401444079:android:3f49b090ed19fc5b45fb1a',
    messagingSenderId: '994401444079',
    projectId: 'ecom-e55f5',
    storageBucket: 'ecom-e55f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7EQlFCNRCgpCGurtieZXwsc89geBq1vE',
    appId: '1:994401444079:ios:cde41600dda3352f45fb1a',
    messagingSenderId: '994401444079',
    projectId: 'ecom-e55f5',
    storageBucket: 'ecom-e55f5.appspot.com',
    iosClientId: '994401444079-433rh87r4f52pg7k1uia60ad7ml4q88v.apps.googleusercontent.com',
    iosBundleId: 'com.example.advisor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7EQlFCNRCgpCGurtieZXwsc89geBq1vE',
    appId: '1:994401444079:ios:cde41600dda3352f45fb1a',
    messagingSenderId: '994401444079',
    projectId: 'ecom-e55f5',
    storageBucket: 'ecom-e55f5.appspot.com',
    iosClientId: '994401444079-433rh87r4f52pg7k1uia60ad7ml4q88v.apps.googleusercontent.com',
    iosBundleId: 'com.example.advisor',
  );
}
